version: '2'
services:
  database:
    image: postgres:9.5.2
    ports:
      - 5432:5432
    volumes:
      - psql-data:/var/lib/postgresql/data
  app:
    image: python:3.4-slim
    links:
      - database
    ports:
      - 8000:8000
    volumes:
      - .:/application
      - ~/.ssh:/root/.ssh
      - app-python-site-packages:/usr/local/lib/python3.4/site-packages
      - app-usr-local-bin:/usr/local/bin
volumes:
  app-python-site-packages:
    driver: local
  psql-data:
    driver: local
  app-usr-local-bin:
    driver: local

